services:
  server:
    build:
      context: ./Docker/server
      dockerfile: Dockerfile
    restart: always
    tty: true
    env_file:
      - .env.mysql
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      - db
    networks:
      - axum_ddd_rust_network
  db:
    build:
      context: ./Docker/mysql
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.mysql
    ports:
      - "3309:3306" # map MySQL port 3306 to host port 3309 to avoid conflicts
    volumes:
      - ./Docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - axum_ddd_rust_network

networks:
  axum_ddd_rust_network:
    driver: bridge

