services:
  server:
    build:
      context: ./Docker/server
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      - db
  db:
    build:
      context: ./Docker/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
    ports:
      
      - "3309:3306" # map MySQL port 3306 to host port 3309 to avoid conflicts
    volumes:
      - ./Docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

