[package]
name = "main"
version = "0.1.0-rc.1"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
usecase = { path = "../usecase" }
infrastructure = { path = "../infrastructure" }
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tower.workspace = true
anyhow.workspace = true
sqlx.workspace = true
dotenv.workspace = true


# anyhow = "1.0.97"
# async-trait = "0.1.88"
# mockall = "0.13.1"
# tokio = { version = "1", features = ["full"] }
# serde = { version = "1", features = ["derive"] }
# serde_json = "1"
# sqlx = { version = "0.8.3", features = ["mysql", "runtime-tokio-native-tls"] }
# tracing = "0.1.41"
